[package]
name = "yatangaki"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version  = "0.12.0", features = ["advanced", "tokio"] }
iced_aw = "0.9"
tokio = { version = "1", features = ["time", "sync", "net", "macros", "rt"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"

[profile.dev]
debug = 0
strip = "debuginfo"
